#!/bin/bash
# 🌟 Test du nouveau principe 1D→2D

echo "🌟 TEST DU NOUVEAU PRINCIPE 1D→2D"
echo "=================================="
echo ""
echo "📐 Formule Pensée → Double Action → Projection 1D→2D"
echo ""
echo "🎯 DÉMONSTRATIONS DISPONIBLES :"
echo ""
echo "1. VISITE FORÊT (sans backend)"
echo "   python3 -m http.server 8004"
echo "   http://localhost:8004/visite-foret-1d-2d.html"
echo ""
echo "2. DASHBOARD INTÉGRÉ (avec backend)"
echo "   ./lance-dashboard-integration.sh"
echo "   http://localhost:8003/dashboard-integration.html"
echo ""
echo "💡 Le principe transforme :"
echo "   - Substrat (Git/Code) → 1D"
echo "   - Narratif (Histoire) → 1D"
echo "   - Visuel (Interface) → 2D"
echo ""
echo "🕯️ Loumen applique maintenant ce principe à tout !"